export const projectData2 = [
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1753891475/ARC_Meatball_68299_w9tjmw.webp",
    category: "Web Development",
    name: "NASA HADES Tool - Interactive GUI",
    description:
      "Designed and developed an interactive GUI for NASA's HADES tool using Electron.js, React, Redux, TypeScript, and PouchDB, enabling early-stage safety assessments of autonomous airspace systems and improving workflow efficiency and hazard identification speed by over 65% through simulation-based analysis.",
    link: "",
    award: "NASA Ames Research Center",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1753891475/ARC_Meatball_68299_w9tjmw.webp",
    category: "AI Research",
    name: "Graph-RAG AI Research",
    description:
      "Competitive AI research paper coming soon. Conducted Graph-RAG AI Research at NASA Ames Research Center.",
    link: "",
    award: "NASA Ames Research Center",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1753891371/Screenshot_2025-07-30_at_9.02.46_AM_rpeg8b.png",
    category: "Cybersecurity",
    name: "Custom Volatility3 Plugin for AI/ML Memory Analysis",
    description:
      "Custom Volatility3 plugin on Linux to analyze memory dumps from AI/ML processes, achieving 95% extraction accuracy of neural network-related Python objects. Part of AI Security Research at Georgia Tech CyFI Lab.",
    link: "https://github.com/Takella6315/Volatility-gc-plugin",
    award: "Georgia Tech CyFI Lab",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1740707040/1740453947182_iy6ko4.jpg",
    category: "AI/Startup",
    name: "SynesisAI - BioTech AI Startup",
    description:
      "Founded SynesisAI, a BioTech AI startup building a platform to accelerate drug discovery by predicting protein-protein interactions using protein language models, with 3D structural visualizations. 1st Overall at GT Hackalytics Datathon. Seed-Funding from Georgia Tech Create-X.",
    link: "https://www.synesisai.me/",
    award: "1st Overall at GT Hackalytics Datathon | Seed-Funding from Georgia Tech Create-X",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730754324/Screenshot_2024-11-04_at_4.04.49_PM_r24s6l.png",
    category: "Cybersecurity",
    name: "Network Traffic Visualization",
    description:
      "Developed a Python tool to parse Packet Capture (PCAP) files generated by Wireshark. The tool maps IP addresses to physical locations using a geolocation database. Technologies: Python, Wireshark, GeoIP database, SMTP, Data Visualization, Network Protocol Analysis.",
    link: "https://github.com/Takella6315/network-packet-tracing",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730757945/Screenshot_2024-11-04_at_5.05.37_PM_nwgylu.png",
    category: "Web Development/Startup",
    name: "Reffy Inc. - Founding Engineer",
    description:
      "Designed and implemented a scalable, secure distributed infrastructure using TypeScript, React, Next.js, PostgreSQL, Golang, GCP, Azure, and Docker, reducing customer and enterprise labor by 80% through a client-facing web application and microservice backend. Currently partnered with many top universities, such as Emory. Expecting more than 50,000 users this year.",
    link: "https://www.reffy.ai/",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730758248/Screenshot_2024-11-04_at_5.09.59_PM_x9uinc.png",
    category: "AI/Research",
    name: "Brain Tumor Detection using CNNs",
    description:
      "Improved brain tumor detection accuracy by 30% by automating MRI scan analysis using CNNs built with TensorFlow; used Python, NumPy, OpenCV, and scikit-learn for data processing and model training. Research conducted at Purdue VIPER Lab.",
    link: "",
    award: "Purdue VIPER Lab",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730754693/Screenshot_2024-11-04_at_4.11.25_PM_gm18ru.png",
    category: "Web Development",
    name: "Prescription Management Software",
    description:
      "Created a prototype web application that tracks and reminds elderly users of active prescriptions.",
    link: "https://github.com/Takella6315/Prescription-Management",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730758013/Screenshot_2024-11-04_at_5.06.40_PM_nuy1go.png",
    category: "Web Development",
    name: "Bragsheet.ai",
    description:
      "Platform to help students write bragsheets.",
    link: "https://bragsheet.ai/",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730836014/Keylogger_Graphic_pxkdho.avif",
    category: "Cybersecurity",
    name: "Keylogger w/ SMTP transmit",
    description:
      "Cybersecurity project demonstrating network security concepts.",
    link: "https://github.com/Takella6315/Cybersecurity-Keylogger",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730836155/Image_Encryption_Graphic_ka4gcf.jpg",
    category: "Cybersecurity",
    name: "Image Encryption via image-key",
    description:
      "Image encryption project for secure data transmission.",
    link: "https://github.com/Takella6315/Image-Encryption",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730758111/Agar.io_Remake_Image_qcx4um.png",
    category: "Web Development",
    name: "Agar.io Remake",
    description:
      "Multiplayer game remake demonstrating real-time web development skills.",
    link: "https://github.com/Takella6315/Agar.io-remake",
  },
];
