export const projectData2 = [
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1753891475/ARC_Meatball_68299_w9tjmw.webp",
    category: "Web Development",
    name: "COMING SOON: Open-Source Risk Assessment Platform",
    description:
      "Coming soon to NASA Github...Open Source Risk assessment platform",
    link: "",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1753891475/ARC_Meatball_68299_w9tjmw.webp",
    category: "AI",
    name: "COMING SOON: Custom Graph RAG AI Research",
    description:
      "Coming soon...AI Research & Paper for NASA",
    link: "",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1753891371/Screenshot_2025-07-30_at_9.02.46_AM_rpeg8b.png",
    category: "Cybersecurity",
    name: "Custom Volatility3 Plugin",
    description:
      "Custom Volatility3 plugin on Linux to analyze memory dumps from AI/ML processes, achieving 95% extraction accuracy of neural network-related Python objects.",
    link: "https://github.com/Takella6315/Volatility-gc-plugin",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1740707040/1740453947182_iy6ko4.jpg",
    category: "AI",
    name: "ProteinAI",
    description:
      "Protein-Protein Interactions Predictor and 3D modeling.",
    link: "https://www.synesisai.me/",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730754324/Screenshot_2024-11-04_at_4.04.49_PM_r24s6l.png",
    category: "Cybersecurity",
    name: "Network Traffic Visualization",
    description:
      "Python tool to parse PCAP files generated by Wireshark. The tool maps IP addresses to physical locations.",
    link: "https://github.com/Takella6315/network-packet-tracing",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730754693/Screenshot_2024-11-04_at_4.11.25_PM_gm18ru.png",
    category: "Web Development",
    name: "Prescription Management Software",
    description:
      "Created a prototype web application that tracks and reminds elderly users of active prescriptions.",
    link: "https://github.com/Takella6315/Prescription-Management",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730757945/Screenshot_2024-11-04_at_5.05.37_PM_nwgylu.png",
    category: "Web Development",
    name: "Reffy.ai",
    description:
      "AI tool that professors are using to manage and write recommendation letters",
    link: "https://www.reffy.ai/",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730758013/Screenshot_2024-11-04_at_5.06.40_PM_nuy1go.png",
    category: "Web Development",
    name: "Bragsheet.ai",
    description:
      "Platform to help students write bragsheets.",
    link: "https://bragsheet.ai/",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730836014/Keylogger_Graphic_pxkdho.avif",
    category: "Cybersecurity",
    name: "Keylogger w/ SMTP trasmit",
    description:
      "",
    link: "https://github.com/Takella6315/Cybersecurity-Keylogger",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730836155/Image_Encryption_Graphic_ka4gcf.jpg",
    category: "Cybersecurity",
    name: "Image Encryption via image-key",
    description:
      "",
    link: "https://github.com/Takella6315/Image-Encryption",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730758111/Agar.io_Remake_Image_qcx4um.png",
    category: "Web Development",
    name: "Agar.io Remake",
    description:
      "",
    link: "https://github.com/Takella6315/Agar.io-remake",
  },
  {
    image:
      "https://res.cloudinary.com/dvt9oo5gl/image/upload/v1730758248/Screenshot_2024-11-04_at_5.09.59_PM_x9uinc.png",
    category: "AI",
    name: "Brain Tumor Detection using CNN/U-net",
    description:
      "",
    link: "",
  },

  
];
